# Run SQL against DuckDB

Paste your SQL here and run to fetch data from the parquet dataset.

In [6]:
import sys
sys.path.insert(0, "..")

from dotenv import load_dotenv
load_dotenv("../.env")

from retrieval.graph.tool.SQLvalidator import _get_connection

In [ ]:
# Paste your SQL here
sql = """
SELECT 
    COUNT(DISTINCT person_id) AS total_patients 
FROM 
    condition_occurrence 
WHERE 
    condition_source_value IN ('C18', 'C19', 'C20') 
    AND EXTRACT(YEAR FROM condition_start_date) = 2020
"""

con = _get_connection()
df = con.execute(sql.strip()).fetchdf()
print(f"Rows: {len(df)}")
df

Rows: 1

   total_patients
0              19

In [11]:
sql="""
SELECT 
    COUNT(DISTINCT person_id) AS total_patients 
FROM 
    condition_occurrence 
WHERE 
    condition_start_date BETWEEN '2020-01-01' AND '2020-12-31';"""

con = _get_connection()
df = con.execute(sql.strip()).fetchdf()
print(f"Rows: {len(df)}")
df

Rows: 1

   total_patients
0              19